import React from 'react';

import { Box, Typography, useTheme } from '@mui/material';
import { tokens } from '../themes/MyTheme';

// React Components
import Header from '../components/Header';

function ApiDocs() {
  const theme = useTheme();
  const colours = tokens(theme.palette.mode);

  return (
    <Box px={5} pb={5}>
      <Box
        display="flex"
        flexDirection="column"
      >
        <Header
          title="API Documentation"
          subtitle="iOrganiseAPI Endpoint Info"
        />

        <Box mt={4} p={5} backgroundColor={colours.primary[400]} borderRadius="5px">
          <Box mb={10}>
            <Box>
              <Box mb={3}>
                <Typography variant="h3">
                  Transcribe Audio
                </Typography>
                <Typography>
                  [POST]: /transcribe-audio
                </Typography>
              </Box>

              <Box mb={3}>
                <Typography variant="h5">API Endpoint</Typography>
                <Typography>{import.meta.env.VITE_API_BASE_URL}transcribe-audio</Typography>
              </Box>

              <Box mb={3}>
                <Typography variant="h5">Params:</Typography>
                <Box mb={2}>
                  <Typography>
                    asr_model: <code>string (see AsrModels)</code>
                  </Typography>
                </Box>
                <Box mb={2}>
                  <Typography>
                    content_summary: <code>boolean</code>
                  </Typography>
                </Box>
                <Box mb={2}>
                  <Typography>
                    llm: <code>string (see LlmModels)</code>
                  </Typography>
                </Box>
              </Box>

              <Box mb={3}>
                <Typography variant="h5">Enums:</Typography>
                <Box mb={2}>
                  <Typography>AsrModels:</Typography>
                  <Box ml={2}>
                    <Typography><code>"small"</code></Typography>
                    <Typography><code>"small_sg"</code></Typography>
                    <Typography><code>"medium"</code></Typography>
                  </Box>
                </Box>

                <Box mb={2}>
                  <Typography>LlmModels:</Typography>
                  <Box ml={2}>
                    <Typography><code>"mistral_7b"</code></Typography>
                    <Typography><code>"llama_8b"</code></Typography>
                    <Typography><code>"mistral_22b"</code></Typography>
                  </Box>
                </Box>
              </Box>

              <Box mb={3}>
                <Typography variant="h5">Body:</Typography>
                <Typography>
                  files: <code>array</code> (of file objects)
                </Typography>
              </Box>

              <Box>
                <Typography variant="h5">Example Response:</Typography>
                <Typography mb={2}>Example of the response the API will provide with diarisation enabled and with the second file encountering an error.</Typography>
                <Typography component="pre">
                  {`{
  "1": {
    "filename": "audio1.wav",
    "language": "en",
    "segments": [
      {
        "start": 0.0,
        "end": 3.0,
        "text": "Hello, this is the first segment."
      },
      {
        "start": 3.0,
        "end": 6.0,
        "text": "This is the second segment."
      }
    ],
    "summary": "This is the summary generated by the LLM"
  }
}`}
                </Typography>
              </Box>
            </Box>
          </Box>

          <Box>
            <Box mb={3}>
              <Typography variant="h3">
                Get Device
              </Typography>
              <Typography>
                [GET]: /get-device
              </Typography>
            </Box>

            <Box mb={3}>
              <Typography variant="h5">API Endpoint</Typography>
              <Typography>{import.meta.env.VITE_API_BASE_URL}get-device</Typography>
            </Box>

            <Box>
              <Typography variant="h5">Example Response:</Typography>
              <Typography mb={2}>Example response which shows the device your models are loaded on.</Typography>
              <Typography component="pre">
                {`{
  "cuda"
}`}
              </Typography>
            </Box>
          </Box>


        </Box>
      </Box>
    </Box>
  )
}

export default ApiDocs